"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

import { Loader } from "@/components/icons";
import { Button } from "@/components/ui/button";
import { FieldError, FieldLabel, Input, Select } from "@/components/ui/field";
import { accommodationPreferences, foodPreferences, travelStyles } from "@/lib/planner-options";
import type { Itinerary, TripRequest } from "@/lib/trip-schema";

type FormValues = { destination: string; budget: string; currency: TripRequest["currency"]; duration: string; travelers: string; style: string; accommodation: string; food: string };
type FormErrors = Partial<Record<keyof FormValues, string>>;
const initialValues: FormValues = { destination: "", budget: "", currency: "INR", duration: "", travelers: "1", style: "", accommodation: "", food: "" };
const loadingMessages = ["Planning your trip…", "Finding places that fit your budget…", "Building your itinerary…"];

export function TripPlanningForm() {
  const router = useRouter();
  const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState<FormErrors>({}); const [isSubmitting, setIsSubmitting] = useState(false); const [formError, setFormError] = useState(""); const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);
  useEffect(() => { if (!isSubmitting) return; const interval = window.setInterval(() => setLoadingMessageIndex((index) => (index + 1) % loadingMessages.length), 2200); return () => window.clearInterval(interval); }, [isSubmitting]);
  const update = (key: keyof FormValues) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setValues((current) => ({ ...current, [key]: event.target.value })); setErrors((current) => ({ ...current, [key]: undefined })); setFormError(""); };
  function validate() { const next: FormErrors = {}; if (values.destination.trim().length < 2) next.destination = "Please enter a destination."; if (!values.budget || Number(values.budget) <= 0) next.budget = "Enter a budget greater than zero."; if (!values.duration || Number(values.duration) < 1 || Number(values.duration) > 30) next.duration = "Choose between 1 and 30 days."; if (!values.travelers || Number(values.travelers) < 1 || Number(values.travelers) > 12) next.travelers = "Choose between 1 and 12 travelers."; if (!values.style) next.style = "Choose a travel style."; if (!values.accommodation) next.accommodation = "Choose an accommodation preference."; if (!values.food) next.food = "Choose a food preference."; return next; }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const next = validate(); setErrors(next); if (Object.keys(next).length) return; setIsSubmitting(true); setFormError(""); setLoadingMessageIndex(0); try { const requestBody = { ...values, budget: Number(values.budget), duration: Number(values.duration), travelers: Number(values.travelers) }; const response = await fetch("/api/trips/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(requestBody) }); const payload = await response.json() as { itinerary?: Itinerary; error?: string; fieldErrors?: Record<string, string[]> }; if (!response.ok || !payload.itinerary) { if (payload.fieldErrors) setErrors(Object.fromEntries(Object.entries(payload.fieldErrors).map(([key, messages]) => [key, messages?.[0]])) as FormErrors); setFormError(payload.error ?? "Something went wrong while creating your itinerary. Please try again."); return; } sessionStorage.setItem("roamly-current-itinerary", JSON.stringify({ itinerary: payload.itinerary, request: requestBody })); window.dispatchEvent(new Event("roamly-storage-update")); router.push("/plan/results"); } catch { setFormError("We couldn’t reach the planning service. Please check your connection and try again."); } finally { setIsSubmitting(false); } }
  return <form noValidate onSubmit={submit} className="rounded-3xl border border-[#e8e3db] bg-white p-6 shadow-[0_18px_55px_-35px_rgba(22,50,79,0.35)] sm:p-8"><div className="mb-7"><h2 className="text-2xl font-semibold tracking-tight text-[#16324f]">Trip details</h2><p className="mt-1.5 text-sm leading-6 text-slate-500">Every field helps tailor the pace and recommendations.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><FieldLabel htmlFor="destination">Destination</FieldLabel><Input id="destination" value={values.destination} onChange={update("destination")} placeholder="e.g. Goa, Manali, Jaipur" aria-invalid={Boolean(errors.destination)} /><FieldError message={errors.destination} /></div><div><FieldLabel htmlFor="budget">Total trip budget</FieldLabel><Input id="budget" type="number" min="1" value={values.budget} onChange={update("budget")} placeholder="e.g. 25000" aria-describedby="budget-help" aria-invalid={Boolean(errors.budget)} /><p id="budget-help" className="mt-1.5 text-xs leading-5 text-slate-500">For the entire group, in the selected currency.</p><FieldError message={errors.budget} /></div><div><FieldLabel htmlFor="currency">Currency</FieldLabel><Select id="currency" value={values.currency} onChange={update("currency")}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>JPY</option></Select></div><div><FieldLabel htmlFor="duration">Duration (days)</FieldLabel><Input id="duration" type="number" min="1" max="30" value={values.duration} onChange={update("duration")} placeholder="e.g. 4" aria-invalid={Boolean(errors.duration)} /><FieldError message={errors.duration} /></div><div><FieldLabel htmlFor="travelers">Travelers</FieldLabel><Input id="travelers" type="number" min="1" max="12" value={values.travelers} onChange={update("travelers")} aria-invalid={Boolean(errors.travelers)} /><FieldError message={errors.travelers} /></div><SelectField id="style" label="Travel style" value={values.style} onChange={update("style")} error={errors.style} options={travelStyles}/><SelectField id="accommodation" label="Accommodation" value={values.accommodation} onChange={update("accommodation")} error={errors.accommodation} options={accommodationPreferences}/><div className="sm:col-span-2"><SelectField id="food" label="Food preference" value={values.food} onChange={update("food")} error={errors.food} options={foodPreferences}/></div></div><Button type="submit" size="lg" disabled={isSubmitting} className="mt-8 w-full bg-[#187764] hover:bg-[#126653]">{isSubmitting ? <><Loader className="size-4 animate-spin" />{loadingMessages[loadingMessageIndex]}</> : "Generate my trip"}</Button>{formError && <div role="alert" className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm leading-6 text-red-700">{formError}</div>}<p className="mt-4 text-center text-xs leading-5 text-slate-500">Costs are estimates; availability, opening hours, and reservations are not guaranteed.</p></form>;
}
function SelectField({ id, label, value, onChange, error, options }: { id: string; label: string; value: string; onChange: (event: React.ChangeEvent<HTMLSelectElement>) => void; error?: string; options: readonly string[] }) { return <div><FieldLabel htmlFor={id}>{label}</FieldLabel><Select id={id} value={value} onChange={onChange} aria-invalid={Boolean(error)}><option value="">Select an option</option>{options.map((option) => <option key={option}>{option}</option>)}</Select><FieldError message={error} /></div>; }
